export type ModelId = "gemini-2.0-flash" | "gpt-4o";
export type Model = {
  id: ModelId;
  name: string;
};

export const availableModels: Model[] = [
  {
    id: "gemini-2.0-flash",
    name: "Gemini 2.5 Flash",
  },
  {
    id: "gpt-4o",
    name: "GPT 4o",
  },
];

export const defaultTemplates = [
  {
    id: "0",
    key: "",
    url: "/default-templates/0.pdf",
    name: "Default Template",
    description: "A basic template for general use.",
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: "default-user",
    fields: [
      {
        id: "field-1",
        key: "NAME",
        description: "The name given to the computer",
        type: "text",
        required: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        documentModelId: "0",
      },
      {
        id: "field-2",
        key: "APPS",
        description: "Required applications for the computer",
        type: "text",
        required: false,
        createdAt: new Date(),
        updatedAt: new Date(),
        documentModelId: "0",
      },
      {
        id: "field-3",
        key: "VISUAL",
        description: "Visual aspects of the computer (ex: RGB, color scheme)",
        type: "text",
        required: false,
        createdAt: new Date(),
        updatedAt: new Date(),
        documentModelId: "0",
      },
      {
        id: "field-4",
        key: "GAMES",
        description: "The purpose of the computer (e.g., gaming, work)",
        type: "text",
        required: false,
        createdAt: new Date(),
        updatedAt: new Date(),
        documentModelId: "0",
      },
      {
        id: "field-5",
        key: "SIZE",
        description: "Tamanho do computador ou gabinete",
        type: "text",
        required: false,
        createdAt: new Date(),
        updatedAt: new Date(),
        documentModelId: "0",
      },
      {
        id: "field-6",
        key: "CPU",
        description: "Processador",
        type: "text",
        required: false,
        createdAt: new Date(),
        updatedAt: new Date(),
        documentModelId: "0",
      },
      {
        id: "field-7",
        key: "PSU",
        description: "Fonte de alimentação",
        type: "text",
        required: false,
        createdAt: new Date(),
        updatedAt: new Date(),
        documentModelId: "0",
      },
      {
        id: "field-8",
        key: "MOTHERBOARD",
        description: "Placa-mãe",
        type: "text",
        required: false,
        createdAt: new Date(),
        updatedAt: new Date(),
        documentModelId: "0",
      },
      {
        id: "field-9",
        key: "RAM",
        description: "Memória RAM",
        type: "text",
        required: false,
        createdAt: new Date(),
        updatedAt: new Date(),
        documentModelId: "0",
      },
      {
        id: "field-10",
        key: "STORAGE",
        description: "Armazenamento",
        type: "text",
        required: false,
        createdAt: new Date(),
        updatedAt: new Date(),
        documentModelId: "0",
      },
      {
        id: "field-11",
        key: "COOLER",
        description: "Cooler do processador",
        type: "text",
        required: false,
        createdAt: new Date(),
        updatedAt: new Date(),
        documentModelId: "0",
      },
      {
        id: "field-12",
        key: "FANS",
        description: "Refrigeração (fans)",
        type: "text",
        required: false,
        createdAt: new Date(),
        updatedAt: new Date(),
        documentModelId: "0",
      },
      {
        id: "field-13",
        key: "TOTAL",
        description: "Valor total",
        type: "text",
        required: false,
        createdAt: new Date(),
        updatedAt: new Date(),
        documentModelId: "0",
      },
      {
        id: "field-14",
        key: "TOTAL_INSTALLMENTS",
        description: "Valor total em 12x",
        type: "text",
        required: false,
        createdAt: new Date(),
        updatedAt: new Date(),
        documentModelId: "0",
      },
      {
        id: "field-15",
        key: "GPU",
        description: "Placa de vídeo",
        type: "text",
        required: false,
        createdAt: new Date(),
        updatedAt: new Date(),
        documentModelId: "0",
      },
      {
        id: "field-16",
        key: "CASE",
        description: "Gabinete",
        type: "text",
        required: false,
        createdAt: new Date(),
        updatedAt: new Date(),
        documentModelId: "0",
      },
      {
        id: "field-17",
        key: "ADDITIONALS",
        description: "Adicionais",
        type: "text",
        required: false,
        createdAt: new Date(),
        updatedAt: new Date(),
        documentModelId: "0",
      },
    ],
  },
];
